export default interface TelegramMessage {
    "_": string,
    "out": boolean,
    "mentioned": boolean,
    "media_unread": boolean,
    "silent": boolean,
    "post": boolean,
    "from_scheduled": boolean,
    "legacy": boolean,
    "edit_hide": boolean,
    "pinned": boolean,
    "noforwads": boolean,
    "id": number,
    "peer_id": {
        "_": string,
        "channel_id": number,
    },
    "date": number,
    "message": string,
    "media": any,
    "entities": any,
    "views": number,
    "forwards": number,
    "edit_date"?: number,
    "reactions"?: any,
}